accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [ # login - logout - sign up (registration) & ...
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('signup', signup_view, name='signup'),
    path('reset', reset_view, name='reset'),
    path('change', change_password, name='change'),
]

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single,name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path("rss/feed/", LatestEntriesFeed()),
    # path('test', test_view)
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from website.views import timer_view

from django.views.static import serve

sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap,
}
from website.views import *
urlpatterns = [
    # re_path(r'^.*$', timer_view),
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('',index_view, name='index'),
    path('about-me',aboutme_view, name='about-me'),
    path('projects', project_view, name='projects'),
    path('contact', contact_view, name='contact'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# from jalali_date import datetime2jalali, date2jalali
from django.urls import reverse
from taggit.managers import TaggableManager

class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    category = models.ManyToManyField(Category)
    tags = TaggableManager()
    counted_view = models.IntegerField(default=0)
    status=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    published_at=models.DateTimeField(auto_now=True, null=True)
    updated_at=models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at',]
    
    def __str__(self):
        return self.title
    
    # def test (self):
    #     return date2jalali(self.published_at)
    
    def get_absolute_url(self) :
        return reverse('blog:single', kwargs={'pid':self.id})
    
class link(models.Model):
    url = models.CharField(max_length=255)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(null=True, blank=True)
    username = models.CharField(max_length=255, null=True, blank=True)
    # subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.first_name+' '+self.last_name

blog/forms.py
from django.forms import ModelForm
from blog.models import link
from blog.models import Comment
from captcha.fields import CaptchaField

class ContactForm(ModelForm):
    class Meta:
        model = link
        fields = '__all__'

class CommentForm(ModelForm) :
    captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = ['post', 'first_name', 'last_name', 'email',  'message',]

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post, Category, Comment
from django.utils import timezone
from django.core.paginator import (Paginator, EmptyPage, PageNotAnInteger)
from django.contrib import messages
from blog.forms import CommentForm

# Create your views here.
def blog_view(request, **kwargs):
    now = timezone.now()
    posts = Post.objects.filter(status=True).exclude(published_at__gte=now)
    if kwargs.get('cat_name'):
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('tag_name'):
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
    category = Category.objects.all()
    cat_dict = {}
    for name in category:
        cat_dict[name] = posts.filter(category=name).count()
    paginator = Paginator(posts, 6)
    try:
        page = request.GET.get('page')
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(1)
    context = {'posts': posts, 'categories':cat_dict}
    return render(request, 'blog.html', context)

def blog_single(request, pid):
    msg = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            msg = messages.add_message(request,messages.SUCCESS, 'کامنت شما در صف بررسی قرار گرفت')
        else:
            msg = messages.add_message(request,messages.ERROR, 'کامنت شما ثبت نشد')
    now = timezone.now()
    posts = Post.objects.filter(status=True).exclude(published_at__gte=now)
    post = get_object_or_404(posts, pk=pid)
    comment = Comment.objects.filter(post=post.id, approved=True)
    prev = Post.objects.filter(status=1, created_at__lt=post.created_at).exclude(pk=post.pk).order_by('-created_at').first()
    next = Post.objects.filter(status=1, created_at__gt=post.created_at).exclude(pk=post.pk).order_by('created_at').first()
    post.counted_view += 1
    post.save()
    form = CommentForm()
    context = {'post': post, 'next': next, 'prev': prev, 'comment':comment, 'msg':msg, 'form':form}
    return render(request, 'single-post.html', context)

templates/change.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>change-password</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body class="my-login-page">
    <div style="padding: 100px;">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="card fat">
						<div class="card-body">
							<div style="text-align: center;">
							<h3 class="card-title">Reset-Password</h3></div>
							<form method="POST" class="my-login-validation" action="{% url 'accounts:change' %}" novalidate="">
								{% csrf_token %}
								<div class="form-group">
									<label>New Password</label>
									<input type="password" class="form-control" name="password" value="" required autofocus>
									<div class="invalid-feedback">
										password is invalid
									</div>
								</div>
                                <div class="form-group">
									<label>Confirm Password</label>
									<input type="password" class="form-control" name="password2" value="" required autofocus>
									<div class="invalid-feedback">
										confirm password is invalid
									</div>
								</div>
                                <div class="form-group">
									<label>Confirm Code</label>
									<input type="text" class="form-control" name="confirm" value="" required autofocus>
									<div class="invalid-feedback">
										confirm code is invalid
									</div>
								</div>
								<div style="text-align: center;"></div>
								<div class="form-group m-0">
									<button type="submit" class="btn btn-primary btn-block">
										<p style="padding-left: 5.5em;"></p>change
									</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	{% if messages %}
        <div id="message-container">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="{% static 'js/main.js' %}"></script>
</div>
</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Main-->
{% if messages %}
<div id="message-container">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
        <!-- <button class="close" aria-label="Close" onclick="closeMessage(this)">
        <span aria-hidden="true">×</span>
        </button> -->
    </div>
    {% endfor %}
</div>
{% endif %}
    <div class="content-wrap ">
        <div class="pt-190 pb-130 bg-linear-gradient shape-parent">
            <!-- Shape-->
            <div class="shape justify-content-end"><img loading="lazy" src="{% static 'img/root/contact-2-shape-547x414.png' %}" alt="" width="547" height="414"></div><!-- Shape-->
            <div class="shape align-items-end justify-content-start"><img loading="lazy" src="{% static 'img/root/contact-2-shape-558x364.png' %}" alt="" width="558" height="364"></div>
            <div class="container">
                <h3 class="m-0 text-center mb-100" data-show="startbox">آیا پروژه ای در ذهن دارید؟</h3>
                
                <div class="row mt-110">
                    <div class="col-lg-8 offset-lg-2">
                        <!-- Form-->
                        <form data-show="startbox" method="post" action="{% url 'website:contact' %}">
                            {% csrf_token %}
                            <div class="row gy-40">
                                <div class="col-12 col-md-6"><input class="form-control" name="first_name" type="text" placeholder="نام"></div>
                                <div class="col-12 col-md-6"><input class="form-control" name="last_name" type="text" placeholder="نام خانوادگی"></div>
                                <div class="col-12 col-md-6"><input class="form-control" name="email" type="email" placeholder="ایمیل"></div>
                                <div class="col-12 col-md-6"><input class="form-control" name="subject" type="text" placeholder="موضوع درخواست"></div>
                                <div class="col-12 mb-10"><textarea class="form-control" name="message" rows="2" placeholder="متن درخواست"></textarea></div>
                                <div class="col-12 mb-10 form-control">{{form.captcha}}</div><div class="col-12 col-lg-3 text-end text-lg-start">
                                    <!-- Button--><button class="btn btn-accent-1">ارسال</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>Login Page</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body class="my-login-page">
    <div style="padding: 100px;">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="card fat">
						<div class="card-body">
							<div style="text-align: center;">
							<h3 class="card-title">Login page</h3></div>
							<form method="POST" class="my-login-validation" action="{% url 'accounts:login' %}" novalidate="">
								{% csrf_token %}
								<div class="form-group">
									<label for="email">E-Mail or Username</label>
									<input id="email" type="text" class="form-control" name="username" value="" required autofocus>
									<div class="invalid-feedback">
										Email is invalid
									</div>
								</div>

								<div class="form-group">
									<label for="password">Password
										<a href="{% url 'accounts:reset' %}" class="float-right">
											Forgot Password?
										</a>
									</label>
									<input id="password" type="password" class="form-control" name="password" required data-eye>
								    <div class="invalid-feedback">
								    	Password is required
							    	</div>
								</div>
								<div style="text-align: center;"></div>
								<div class="form-group m-0">
									<button type="submit" class="btn btn-primary btn-block">
										<p style="padding-left: 5.7em;"></p>Login
									</button>
								</div>
								<div class="mt-4 text-center">
									Don't have an account? <a href="{% url 'accounts:signup' %}">Create One</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	{% if messages %}
        <div id="message-container">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="{% static 'js/main.js' %}"></script>
</div>
</body>
</html>

templates/pagination.html
<div class="pagination btn pgm">
    <span class="step-links">
        {% if posts.has_previous %}
            <pre class="pgn">  </pre><a class="apgn" href="?page=1">first-page</a><pre class="pgn">  </pre>
            <a class="apgn" href="?page={{ posts.previous_page_number }}">previous</a><pre class="pgn">  </pre>
        {% endif %}

        <span class="current">
            <pre class="pgn">  </pre>Page {{ posts.number }} of {{ posts.paginator.num_pages }}<pre class="pgn">  </pre>
            {% for i in posts.paginator.page_range %}
            <pre class="pgn">  </pre><a class="apgn" href="?page={{i}}">{{i}}</a><pre class="pgn">  </pre>
            {% endfor %}
        </span>

        {% if posts.has_next %}
        <pre class="pgn">  </pre><a class="apgn" href="?page={{ posts.next_page_number }}">next</a><pre class="pgn">  </pre>
        <pre class="pgn">  </pre><a class="apgn" href="?page={{ posts.paginator.num_pages }}">last-page</a><pre class="pgn">  </pre>
        {% endif %}
    </span>
</div>

templates/reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>Reset-Password</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body class="my-login-page">
    <div style="padding: 100px;">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="card fat">
						<div class="card-body">
							<div style="text-align: center;">
							<h3 class="card-title">Reset-Password</h3></div>
							<form method="POST" class="my-login-validation" action="{% url 'accounts:reset' %}" novalidate="">
								{% csrf_token %}
								<div class="form-group">
									<label>E-Mail</label>
									<input id="email" type="email" class="form-control" name="email" value="" required autofocus>
									<div class="invalid-feedback">
										Email is invalid
									</div>
								</div>
								<div style="text-align: center;"></div>
								<div class="form-group m-0">
									<button type="submit" class="btn btn-primary btn-block">
										<p style="padding-left: 5.7em;"></p>Reset
									</button>
								</div>
								<div class="mt-4 text-center">
									Don't have an account? <a href="{% url 'accounts:signup' %}">Create One</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	{% if messages %}
        <div id="message-container">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="{% static 'js/main.js' %}"></script>
</div>
</body>
</html>

templates/single-post.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
<!-- Main-->

<div class="content-wrap ">
  <div class="py-240 position-relative">
    <div class="background">
      <div class="background-image jarallax" data-jarallax data-speed="0.8"><img class="jarallax-img" loading="lazy"
          src="{{post.image.url}}" alt=""></div>
    </div>
  </div>
  <div class="container">
    <div class="row pt-120 pb-60">
      <div class="col-12 col-lg-8 offset-lg-2">{% for tag in post.tags.all %}
        <div class="subtitle mb-15 font-size-15 fw-medium text-gray-dark"><a class="atag"
            href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a><span
            class="sep-dot"></span>{{post.published_at|date:'Y / m / d'}}<span class="sep-dot"></span>{{post.author.get_full_name}}<span
            class="sep-dot"></span>{{post.counted_view}} view's

        </div>{% endfor %}
        <h3 class="m-0 ps-30">{{post.title}}</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-lg-8 offset-lg-2">
        <p>{{post.content|safe}}</p>
      </div>
    </div>
<!-- <div style="text-align: center;">
  <div class="btn pgm">
    <div style="text-align: center;">
      {% if post.id > prev.id %}
      <a href="{{ prev.id }}" style="font-size: larger; color: brown;">Prev-Post</a>
      {% endif %}
      <pre style="display: inline;">    </pre>
      {% if next.id > post.id %}
      <a href="{{ next.id }}" style="font-size: larger; color: brown;">Next-Post</a>
      {% endif %}
    </div></br></hr>
  </div>
</div> -->
<div style="text-align: center;">
  <div class="btn pgm">
    <div style="text-align: center;">
      {% if post.id > prev.id %}
      <a href="{{ prev.id }}" style="font-size: larger; color: brown;">Prev-Post</a>
      {% endif %}
      {% if post.id > prev.id and next.id > post.id %}
      <pre style="display: inline;">    </pre>
      {% endif %}
      {% if next.id > post.id %}
      <a href="{{ next.id }}" style="font-size: larger; color: brown;">Next-Post</a>
      {% endif %}
    </div></br></hr>
  </div>
</div>
    <!--  -->
    <div class="col-12 col-lg-8 offset-lg-2">
    <hr style="color: black;">
    </div>
    <div class="col-12 col-lg-8 offset-lg-2">
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
      <!--  -->
      <link href="{% static 'css/commenting.css' %}" rel="stylesheet">
      <!--  -->

      <div class="container bootdey">
        <div class="col-md-12 bootstrap snippets">
          <div class="panel">
            {% if request.user.is_authenticated %}
            <div class="panel-body">
            <form method="post" action="{% url 'blog:single' pid=post.id %}">
            {% csrf_token %}
              <textarea class="form-control" rows="4" name="message" placeholder="نظر شما چیست؟"></textarea>
              {{form.captcha}}
              <input type="hidden" name="post" value="{{post.id}}">
              <input type="hidden" name="first_name" value="{{request.user.first_name}}">
              <input type="hidden" name="last_name" value="{{request.user.last_name}}">
              <input type="hidden" name="email" value="{{request.user.email}}">
              <input type="hidden" name="username" value="{{request.user.username}}">
              <div class="mar-top clearfix">
                <button class="btn btn-sm btn-primary pull-right" type="submit"><i class="fa fa-pencil fa-fw"></i>
                  Share</button>
              </div>
            </form>
              
            </div>
            {% else %}
            <p>برای ایجاد کامنت ابتدا <a style="color: red;" href="{% url 'accounts:login' %}">وارد</a> شوید</p>
            <p>حساب کاربری ندارید؟ <a style="color: red;" href="{% url 'accounts:signup' %}">ساخت حساب کاربری</a></p>
          </br>
            {% endif %}
          </div>
          <div class="panel">
            <div class="panel-body">
              <!-- Newsfeed Content -->
              <!--===================================================-->
              {% for c in comment %}
              <div class="media-block">
                <div class="media-body">
                  <div class="mar-btm">
                    <p class="text-semibold media-heading box-inline">{{c.first_name}} گفته :</p>
                  </div>
                  <p>{{c.message}}</p>
                  <p class="text-muted text-sm hnt">{{c.created_at|naturaltime}}</p>
                  <hr>

                  <!-- Comments -->
                  <div>
                  </div>
                </div>
              </div>
              {% empty %}
              <P>هیج کامنتی اینجا نیست...</P>
              {% endfor %}
            </div>
          </div>
        </div>
        <!--===================================================-->
        <!-- End Newsfeed Content -->
      </div>
      
      
    </div>
  </br>
<!--  -->
<div class="row mb-130">
  <div class="col-12 col-lg-8 offset-lg-2">
    <hr class="mt-0 mb-25">
    <div class="row justify-content-between gy-10">
      <div class="col-auto"><span class="fw-medium font-size-16 ms-8">برچسب:</span>
        {% for cat in post.category.all %}
        <a class="text-decoration-none text-hover-accent-1" href="#">{{cat.name}} </a>{% if not forloop.last %} ,
        {% endif %}{% endfor %}
      </div>
      <div class="col-auto"><span class="fw-medium font-size-16 ms-10">اشتراک:</span>
        <ul class="nav nav-gap-md d-inline-flex">
          <li class="nav-item"><a class="nav-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="7"
                height="13" fill="none">
                <path fill="currentColor"
                  d="M5.15 2.158H6.3V.091C6.102.063 5.42 0 4.625 0 2.966 0 1.83 1.077 1.83 3.054v1.821H0v2.31h1.83V13h2.244V7.186H5.83l.28-2.311H4.073V3.283c0-.668.174-1.125 1.076-1.125Z" />
              </svg></a></li>
          <li class="nav-item"><a class="nav-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16"
                height="13" fill="none">
                <path fill="currentColor"
                  d="M14.324 3.849c.01.13.01.262.01.393 0 3.991-3.155 8.59-8.922 8.59a9.11 9.11 0 0 1-4.814-1.355c.252.028.495.038.757.038a6.434 6.434 0 0 0 3.892-1.29c-1.378-.028-2.533-.898-2.931-2.094.194.028.388.046.592.046.281 0 .563-.037.825-.103C2.296 7.794 1.22 6.58 1.22 5.111v-.037a3.25 3.25 0 0 0 1.417.383c-.844-.542-1.398-1.468-1.398-2.515 0-.56.156-1.075.427-1.524C3.21 3.251 5.53 4.448 8.13 4.578a3.288 3.288 0 0 1-.077-.692c0-1.664 1.398-3.02 3.135-3.02.903 0 1.718.365 2.291.954a6.32 6.32 0 0 0 1.99-.729 3.035 3.035 0 0 1-1.378 1.664 6.477 6.477 0 0 0 1.805-.467 6.61 6.61 0 0 1-1.572 1.56Z" />
              </svg></a></li>
          <li class="nav-item"><a class="nav-link" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="11"
                height="14" fill="none">
                <path fill="currentColor"
                  d="M5.844 0C2.904 0 0 1.919 0 5.024 0 6.998 1.134 8.12 1.822 8.12c.283 0 .447-.774.447-.992 0-.261-.68-.817-.68-1.902 0-2.256 1.754-3.854 4.023-3.854 1.95 0 3.394 1.085 3.394 3.08 0 1.489-.61 4.283-2.586 4.283-.714 0-1.324-.505-1.324-1.229 0-1.06.756-2.087.756-3.18 0-1.858-2.69-1.521-2.69.723 0 .471.06.993.276 1.422-.396 1.666-1.204 4.149-1.204 5.865 0 .53.078 1.052.13 1.582.097.107.048.096.197.043 1.444-1.936 1.392-2.315 2.045-4.848.353.657 1.264 1.01 1.985 1.01C9.634 10.123 11 7.22 11 4.603 11 1.818 8.542 0 5.844 0Z" />
              </svg></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>

</div>
{% if messages %}
        <div id="message-container">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
{% endblock %}